services:
  hono:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./storage:/app/storage
    command: yarn dev
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
